### PR TITLE
fix invalid size of ipset while reducing non-optimized ipsets

### LINKED ISSUE #18: Reduce on unsorted ips generate warrning
When I use reduce with unsorted ip list, I get strange errors. (Data for example.list are bellow.)

```bash
iprange --reduce-factor 20 example.list
```
```txt
iprange: WARNING: invalid range reversed start=x.x.x.80 end=0.0.x.x
iprange: WARNING: invalid range reversed start=x.x.x.96 end=0.0.x.x
iprange: WARNING: invalid range reversed start=255.255.255.255 end=0.0.0.0
iprange: WARNING: invalid range reversed start=x.x.x.160 end=0.0.127.x
```
x seems random.

But when I provide same data into stdin, it works without error:

```bash
cat example.list | iprange --reduce-factor 20
```

It also works if I optimize data first:
```bash
iprange -J example.list > example2.list
iprange --reduce-factor 20 example2.list
```

I'm using version [1.0.3+ds-1](https://packages.debian.org/stretch/iprange) from debian stretch, but i'm on debian jessie, so it's possible it is somehow related.

```bash
cat > example.list <<EOF
216.144.250.150
69.162.124.226
69.162.124.227
69.162.124.228
69.162.124.229
69.162.124.230
69.162.124.231
69.162.124.232
69.162.124.233
69.162.124.234
69.162.124.235
69.162.124.236
69.162.124.237
63.143.42.242
63.143.42.243
63.143.42.244
63.143.42.245
63.143.42.246
63.143.42.247
63.143.42.248
63.143.42.249
63.143.42.250
63.143.42.251
63.143.42.252
63.143.42.253
46.137.190.132
122.248.234.23
188.226.183.141
178.62.52.237
54.79.28.129
54.94.142.218
104.131.107.63
54.67.10.127
54.64.67.106
159.203.30.41
46.101.250.135
18.221.56.27
EOF
```

### PR DESCRIPTION
**Pull request by ktsaou**
fixes #18

### CODE REVIEW

**Comment by ktsaou** [comment]
@philwhineray travis is complaining about `fakeroot`. When you find some time, have a look...

**Comment by philwhineray** [comment]
OK. Fixed. I will organise a release ASAP.

**Comment by philwhineray** [comment]
Released as v1.0.4

**Comment by ktsaou** [comment]
You rock!

**Pull request merged**
